// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SciQualMonitorWpfApp.Helpers;

#nullable disable

namespace SciQualMonitorWpfApp.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.17");

            modelBuilder.Entity("SciQualMonitorWpfApp.Models.Adviser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AcademicDegree")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Patronym")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Advisers");
                });

            modelBuilder.Entity("SciQualMonitorWpfApp.Models.ArticlesCount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GraduateId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("YearFiveArticles")
                        .HasColumnType("INTEGER");

                    b.Property<int>("YearFourArticles")
                        .HasColumnType("INTEGER");

                    b.Property<int>("YearOneArticles")
                        .HasColumnType("INTEGER");

                    b.Property<int>("YearThreeArticles")
                        .HasColumnType("INTEGER");

                    b.Property<int>("YearTwoArticles")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GraduateId");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("SciQualMonitorWpfApp.Models.Expulsion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExpulsionReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ExpulsionYear")
                        .HasMaxLength(4)
                        .HasColumnType("INTEGER");

                    b.Property<int>("GraduateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GraduateId");

                    b.ToTable("Expulsions");
                });

            modelBuilder.Entity("SciQualMonitorWpfApp.Models.Graduate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BIPAdmissionYear")
                        .HasMaxLength(4)
                        .HasColumnType("INTEGER");

                    b.Property<int>("BIPContractYear")
                        .HasMaxLength(4)
                        .HasColumnType("INTEGER");

                    b.Property<string>("BIPDepartment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BIPGraduateType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BIPSpecialty")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BIPStudyingForm")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BIPThesisTheme")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DateOfBirth")
                        .HasMaxLength(4)
                        .HasColumnType("INTEGER");

                    b.Property<string>("ForeignCommentary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ForeignCountry")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GraguationYear")
                        .HasMaxLength(4)
                        .HasColumnType("INTEGER");

                    b.Property<string>("InGraduationYear")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsForeigner")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Patronym")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SciAdviserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ThesisDefenceYear")
                        .HasMaxLength(4)
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SciAdviserId");

                    b.ToTable("Graduates");
                });

            modelBuilder.Entity("SciQualMonitorWpfApp.Models.GraduateMastersDegree", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GraduateId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MastersDegreeYear")
                        .HasMaxLength(4)
                        .HasColumnType("INTEGER");

                    b.Property<string>("MastersThesisTheme")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GraduateId");

                    b.ToTable("MastersDegrees");
                });

            modelBuilder.Entity("SciQualMonitorWpfApp.Models.HigherEducationGraduation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GraduateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GraduationInstitutionTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GraduationQualification")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GraduationSpecialty")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GraduationYear")
                        .HasMaxLength(4)
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GraduateId");

                    b.ToTable("Graduations");
                });

            modelBuilder.Entity("SciQualMonitorWpfApp.Models.Interruption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GraduateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InterruptionReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InterruptionYear")
                        .HasMaxLength(4)
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GraduateId");

                    b.ToTable("Interruptions");
                });

            modelBuilder.Entity("SciQualMonitorWpfApp.Models.PapersCount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GraduateId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MonoCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GraduateId");

                    b.ToTable("Papers");
                });

            modelBuilder.Entity("SciQualMonitorWpfApp.Models.Restoration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GraduateId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RestorationYear")
                        .HasMaxLength(4)
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GraduateId");

                    b.ToTable("Restorations");
                });

            modelBuilder.Entity("SciQualMonitorWpfApp.Models.SemiAnnualCertification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GraduateId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("YearFiveCertOne")
                        .HasMaxLength(1)
                        .HasColumnType("INTEGER");

                    b.Property<int>("YearFiveCertTwo")
                        .HasMaxLength(1)
                        .HasColumnType("INTEGER");

                    b.Property<int>("YearFourCertOne")
                        .HasMaxLength(1)
                        .HasColumnType("INTEGER");

                    b.Property<int>("YearFourCertTwo")
                        .HasMaxLength(1)
                        .HasColumnType("INTEGER");

                    b.Property<int>("YearOneCertOne")
                        .HasMaxLength(1)
                        .HasColumnType("INTEGER");

                    b.Property<int>("YearOneCertTwo")
                        .HasMaxLength(1)
                        .HasColumnType("INTEGER");

                    b.Property<int>("YearThreeCertOne")
                        .HasMaxLength(1)
                        .HasColumnType("INTEGER");

                    b.Property<int>("YearThreeCertTwo")
                        .HasMaxLength(1)
                        .HasColumnType("INTEGER");

                    b.Property<int>("YearTwoCertOne")
                        .HasMaxLength(1)
                        .HasColumnType("INTEGER");

                    b.Property<int>("YearTwoCertTwo")
                        .HasMaxLength(1)
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GraduateId");

                    b.ToTable("Certifications");
                });

            modelBuilder.Entity("SciQualMonitorWpfApp.Models.ThesesCount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GraduateId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("YearFiveTheses")
                        .HasColumnType("INTEGER");

                    b.Property<int>("YearFourTheses")
                        .HasColumnType("INTEGER");

                    b.Property<int>("YearOneTheses")
                        .HasColumnType("INTEGER");

                    b.Property<int>("YearThreeTheses")
                        .HasColumnType("INTEGER");

                    b.Property<int>("YearTwoTheses")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GraduateId");

                    b.ToTable("Theses");
                });

            modelBuilder.Entity("SciQualMonitorWpfApp.Models.Transfer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GraduateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TransferInfo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GraduateId");

                    b.ToTable("Transfers");
                });

            modelBuilder.Entity("SciQualMonitorWpfApp.Models.ArticlesCount", b =>
                {
                    b.HasOne("SciQualMonitorWpfApp.Models.Graduate", "Graduate")
                        .WithMany()
                        .HasForeignKey("GraduateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Graduate");
                });

            modelBuilder.Entity("SciQualMonitorWpfApp.Models.Expulsion", b =>
                {
                    b.HasOne("SciQualMonitorWpfApp.Models.Graduate", "Graduate")
                        .WithMany()
                        .HasForeignKey("GraduateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Graduate");
                });

            modelBuilder.Entity("SciQualMonitorWpfApp.Models.Graduate", b =>
                {
                    b.HasOne("SciQualMonitorWpfApp.Models.Adviser", "Adviser")
                        .WithMany()
                        .HasForeignKey("SciAdviserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adviser");
                });

            modelBuilder.Entity("SciQualMonitorWpfApp.Models.GraduateMastersDegree", b =>
                {
                    b.HasOne("SciQualMonitorWpfApp.Models.Graduate", "Graduate")
                        .WithMany()
                        .HasForeignKey("GraduateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Graduate");
                });

            modelBuilder.Entity("SciQualMonitorWpfApp.Models.HigherEducationGraduation", b =>
                {
                    b.HasOne("SciQualMonitorWpfApp.Models.Graduate", "Graduate")
                        .WithMany()
                        .HasForeignKey("GraduateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Graduate");
                });

            modelBuilder.Entity("SciQualMonitorWpfApp.Models.Interruption", b =>
                {
                    b.HasOne("SciQualMonitorWpfApp.Models.Graduate", "Graduate")
                        .WithMany()
                        .HasForeignKey("GraduateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Graduate");
                });

            modelBuilder.Entity("SciQualMonitorWpfApp.Models.PapersCount", b =>
                {
                    b.HasOne("SciQualMonitorWpfApp.Models.Graduate", "Graduate")
                        .WithMany()
                        .HasForeignKey("GraduateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Graduate");
                });

            modelBuilder.Entity("SciQualMonitorWpfApp.Models.Restoration", b =>
                {
                    b.HasOne("SciQualMonitorWpfApp.Models.Graduate", "Graduate")
                        .WithMany()
                        .HasForeignKey("GraduateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Graduate");
                });

            modelBuilder.Entity("SciQualMonitorWpfApp.Models.SemiAnnualCertification", b =>
                {
                    b.HasOne("SciQualMonitorWpfApp.Models.Graduate", "Graduate")
                        .WithMany()
                        .HasForeignKey("GraduateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Graduate");
                });

            modelBuilder.Entity("SciQualMonitorWpfApp.Models.ThesesCount", b =>
                {
                    b.HasOne("SciQualMonitorWpfApp.Models.Graduate", "Graduate")
                        .WithMany()
                        .HasForeignKey("GraduateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Graduate");
                });

            modelBuilder.Entity("SciQualMonitorWpfApp.Models.Transfer", b =>
                {
                    b.HasOne("SciQualMonitorWpfApp.Models.Graduate", "Graduate")
                        .WithMany()
                        .HasForeignKey("GraduateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Graduate");
                });
#pragma warning restore 612, 618
        }
    }
}
